import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Android SDK documentation. The API documentation lives in its own plugin
// instance, linked at the bottom so both are reachable from the sidebar.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Android SDK docs',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '.'}],
    },
    {
      type: 'link',
      label: 'API docs',
      href: '/api-docs/corepos-api',
    },
  ],
};

export default sidebars;
