import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the Dokka-generated SDK reference: mirrors the generated folder tree.
const sidebars: SidebarsConfig = {
  sdkReferenceSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
